### ISSUE TITLE
Fix disappearing logo and main menu background

### ISSUE THREAD

**Issue by Brentophillips** [BeehiveNGO/Beta#26]
After navigating to the Listview Module the black Beehive logo disappears and the main menu area changes color. We'd like to keep the logo in place and keep the background white. Problem [screenshot](https://github.com/BeehiveNGO/Beta/blob/master/auxilliary_files/menu-color-250.png).

**Comment by Brentophillips** [comment]
Use the website files in the [Docs](https://github.com/BeehiveNGO/Beta/tree/master/docs) folder. After we fix the two problems then we'll update the beta_files.

**Comment by AniePanwar** [comment]
This issue has been fixed, please download the code from the link https://drive.google.com/file/d/0ByGhRDb4LFh0V2RfckZnVXVKUDA/view?usp=sharing

**Comment by Brentophillips** [comment]
Hey, thanks for the work, that's super cool! I'll upload the code today and
get back to you.

You on GitHub? I'll add you to the team. We also have a staff account, it's
possible folks could use it too.

Best,

Brent
