### ISSUE TITLE
Introduce Team to GitHub

### ISSUE THREAD

**Issue by Brentophillips** [BeehiveNGO/Beta#3]
Introduce team to GitHub

**Comment by Brentophillips** [comment]
Hello Team!

**Comment by wildaces215** [comment]
Hello my name is Craig A, I am currently a college student who is studying Computer and informations sciences! Besides programming I like photography cheers!

**Comment by Brentophillips** [comment]
Hey welcome! What's your profile on GitHub? We're getting the team started
there.

Best,
Brent

**Comment by wildaces215** [comment]
Profile on github? This is my profile.

**Comment by Brentophillips** [comment]
Sorry am on my mobile, will send you invite later today to repo

**Comment by Brentophillips** [comment]
Hey cool, I didn't realize comments thread to email. I started a Contribute repo, check it out and feel free to add some issues there to help us set it up
