### ISSUE TITLE
Front-end technologies to use?

### ISSUE THREAD

**Issue by wildaces215** [BeehiveNGO/Beta#6]
@Brentophillips I saw that you posted images for the UI of the app, what front-end technologies do you think we should use? @roby-boy said React library other alternatives are angularjs or JQuery. Or perhaps something else like ember js?

**Comment by Brentophillips** [comment]
As a suggestion, looking forward to sharing development across teams and individuals, I was thinking starting with Twitter Bootstrap would work well and I'd really like to experiment with React. Check out this link [Bootstrap+React](http://preview.iatistandard.org/index.php?url=http%3A//iati.oxfam.org.uk/xml/oxfamgb-af.xml). At some point I'd like us to build a desktop app using Electron.
