### ISSUE TITLE
Develop Header

### ISSUE THREAD

**Issue by Brentophillips** [BeehiveNGO/Beta#9]
Build an initial header for the header container, for a logo element and a possible modules icon, allowing space for a mobile phone's status bar. See [Design Overview](https://github.com/BeehiveNGO/Beta/blob/master/Beta_Design_Overview.md). Also see [Beehive Logo](https://github.com/BeehiveNGO/Beta/blob/master/images/beehivelogo.png).

**Comment by Brentophillips** [comment]
I've added a [square logo](https://github.com/BeehiveNGO/Beta/blob/master/images/beesq200.png) to experiment with in the images folder.

**Comment by wildaces215** [comment]
I've started with the header will make the pull request soon

**Comment by Brentophillips** [comment]
Feel free to experiment with using Codepen to experiment with ideas. Here's my profile for example: https://codepen.io/Brentophillips/

**Comment by wildaces215** [comment]
Should be close this task?
